### ISSUE TITLE
[enchantment] clickable link

### ISSUE THREAD

**Issue by rebornishard** [SaifurRahmanMohsin/Carousel-Plugin#1]
will it be possible to add link on title ?
optional : open in new tab or current tab
thanks

**Comment by CptMeatball** [comment]
You can overwrite the partial to suit your needs.

**Comment by mohsin** [comment]
Yep that’s correct. You can command+click on the component (I believe Ctrl+click on Windows) and the component’s partial will expand and you can edit it in place with the additional attributes that you need. Alternatively, you can follow [this](https://octobercms.com/docs/cms/components#overriding-partials) to have a separate theme partial that overrides this component.

**Comment by CptMeatball** [comment]
What? That's new to me? Where do I cmd click exactly?

**Comment by mohsin** [comment]
Once you drag the component into the page it should appear something like {% component ‘carousel’ %}. Just keep your mouse over the word component, hold Cmd and double click. Watch it expand!

**Comment by CptMeatball** [comment]
Nice! Is this documented somewhere? I needed this for so long! 

Thanks a bunch!

**Comment by mohsin** [comment]
No idea on that. I know it via messages in the October IRC channel. Here’s a [demo video](https://www.youtube.com/watch?v=6s_0s2VOVQk) of the same. Enjoy! 😄

[![Expanding Component Partial in OctoberCMS](http://img.youtube.com/vi/6s_0s2VOVQk/0.jpg)](http://www.youtube.com/watch?v=6s_0s2VOVQk "Expanding Component Partial in OctoberCMS Video")

**Comment by mdaleo** [comment]
@SaifurRahmanMohsin If I wanted to extend the plugin with another field for the images (e.g. Title, Description, Link) where would I start? It's seems like the carousel plugin is extending the backend class of October, but I'm a little green with this CMS. Any resources you can point me to?

**Comment by mohsin** [comment]
I don’t see why you would need to extend the plugin to solve this. I’ve already mentioned the solution to in this thread. Just use [this technique](#issuecomment-136734580) to edit the partial’s content directly and add the fields.

**Comment by mdaleo** [comment]
Unless I'm missing something, the technique you refer to has to do with editiing the partial of the component that controls the display of the items. I'm trying to associate and additional field in the backend modal of the image. (see attachment)

![screenshot](https://cloud.githubusercontent.com/assets/4529477/11407007/3d290f6e-937e-11e5-93b6-4657b82268e8.png)

**Comment by mohsin** [comment]
That is part of OctoberCMS core and this plugin merely uses that [file upload widget](/SaifurRahmanMohsin/Carousel-Plugin/blob/master/models/carousel/fields.yaml#L10-L13) with the type as image only. You should raise this query in OctoberCMS forum as a [feature request](http://octobercms.com/forum/chan/feature-requests) to allow the file upload widget to have custom user defined fields.

If this custom fields for file upload widget feature is added to OctoberCMS, you can then use this same process of editing component on the page and write something like `{{ image.myfield }}` in the component code to render that field appropriately.
