### ISSUE TITLE
Upload image to carousel size limit

### ISSUE THREAD

**Issue by getlose** [SaifurRahmanMohsin/Carousel-Plugin#10]
I try to upload an image that is bigger than around 2 Mb and I got this error.

"File missing from request"

when I upload an image that is less than around 2 Mb it works fine.  

Is there any configuration for size limit for upload an image for this plugin or on the octobercms itself?

**Comment by mohsin** [comment]
This plugin does not impose any file size restrictions. Any limitations must be from OctoberCMS or your server. I remember reading that OctoberCMS doesn’t impose in file size restrictions either so I recommend you to check your php.ini for [the PHP upload limit](http://stackoverflow.com/a/2184541/997147) or your server config for any file size restrictions imposed by it.
