### ISSUE TITLE
Error when I applied without component 

### ISSUE THREAD

**Issue by surahmans** [SaifurRahmanMohsin/Carousel-Plugin#2]
I got the following error,

<code>An exception has been thrown during the rendering of a template ("The component 'Mohsin\Carousel\Components\Carousel' does not contain a method 'images'.").</code>

although I copy and paste to partial from plugin component

**Comment by mohsin** [comment]
Sorry for the delayed response. Kindly update your OctoberCMS install and let me know if the problem still persists.

**Comment by surahmans** [comment]
Still error. I should add this code in page to resolve this problem.

<code>function onStart() {
    $this->carousel->onRender();
}</code>

**Comment by mohsin** [comment]
Kindly update your OctoberCMS and check and verify whether this issue is resolved. Commit 4cc8048 should have resolved this issue.
