### ISSUE TITLE
Multiple carousels on one page

### ISSUE THREAD

**Issue by mateop** [SaifurRahmanMohsin/Carousel-Plugin#8]
Hi, i am using your plugin with the static pages plugin and whenever there are multiple carousels on a single page they all display the last selected gallery.
Is there a fix or am i doing something wrong?

**Comment by mohsin** [comment]
Interesting bug, thanks for reporting it. Let me verify it and get back to you.

**Comment by mohsin** [comment]
Commit 0a177dc fixes this issue. Feel free to comment should you still face any issue with this, I’ll re-open it. If it’s a different issue, then kindly make a new issue. Thanks. I hope you enjoy my plugin.
